services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:1.0
    container_name: mariadb
    env_file:
      - .env
    # volumes:
    #   - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped
    secrets:
      - db_root_password
      - db_password
  
  # wordpress:
  #   build:
  #     context: ./requirements/wordpress
  #     dockerfile: Dockerfile
  #   image: wordpress:1.0
  #   container_name: wordpress
  #   env_file:
  #     - .env
  #   volumes:
  #     - worpress_data:/var/www/wordpress
  #   networks:
  #     - inception
  #   restart: unless-stopped
  #   secrets:
  #     - db_password
  #     - wp_admin_password
secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt

networks:
  inception:
    driver: bridge

# volumes:
#   mariadb_data:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: /home/frahenin/data/mariadb
  # worpress_data:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: /home/frahenin/data/wordpress
